// AUTO-GENERATED by next-typed-url. DO NOT EDIT.

export type NextjsSuamaRoute =
  | '/'
  | '/[userId]/change-password'
  | '/[userId]/settings'
  | '/appeal/list'
  | '/client/list'
  | '/daily/edit/[id]'
  | '/daily/every'
  | '/daily/mine'
  | '/daily/today'
  | '/forgot-password'
  | '/mission/list'
  | '/project/list'
  | '/reset-password'
  | '/sign-in'
  | '/sign-up'
  | '/trouble/list'
  | '/users'
  | '/verify-email'
  | '/weekly'
  | '/weekly/list/[dates]'
  | '/weekly/list/[dates]/edit/[weeklyReportId]'
  | '/weekly/list/[dates]/register'

type RouteParamValue = string | number
type RouteParamArray = Array<RouteParamValue>
export type NextjsSuamaRouteInput =
  | { route: '/' }
  | { route: '/[userId]/change-password'; params: { userId: RouteParamValue } }
  | { route: '/[userId]/settings'; params: { userId: RouteParamValue } }
  | { route: '/appeal/list' }
  | { route: '/client/list' }
  | { route: '/daily/edit/[id]'; params: { id: RouteParamValue } }
  | { route: '/daily/every' }
  | { route: '/daily/mine' }
  | { route: '/daily/today' }
  | { route: '/forgot-password' }
  | { route: '/mission/list' }
  | { route: '/project/list' }
  | { route: '/reset-password' }
  | { route: '/sign-in' }
  | { route: '/sign-up' }
  | { route: '/trouble/list' }
  | { route: '/users' }
  | { route: '/verify-email' }
  | { route: '/weekly' }
  | { route: '/weekly/list/[dates]'; params: { dates: RouteParamValue } }
  | {
      route: '/weekly/list/[dates]/edit/[weeklyReportId]'
      params: { dates: RouteParamValue; weeklyReportId: RouteParamValue }
    }
  | { route: '/weekly/list/[dates]/register'; params: { dates: RouteParamValue } }

type RouteParams = Record<string, RouteParamValue | RouteParamArray | undefined>
export type NextjsSuamaRouteSearchParamsMap = Record<string, never>
const appendQueryEntry = (entries: string[], key: string, raw: unknown) => {
  if (raw === undefined || raw === null) return
  if (Array.isArray(raw)) {
    for (const item of raw) {
      appendQueryEntry(entries, key, item)
    }
    return
  }
  if (typeof raw === 'string' || typeof raw === 'number' || typeof raw === 'boolean') {
    entries.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(raw))}`)
    return
  }
  throw new Error(`Unsupported query value for key "${key}"`)
}

const serializeQuery = (query: Record<string, unknown>) => {
  const entries: string[] = []
  for (const [key, value] of Object.entries(query)) {
    appendQueryEntry(entries, key, value)
  }
  return entries.join('&')
}

const encodeParam = (value: RouteParamValue) => encodeURIComponent(String(value))
const buildPath = (route: NextjsSuamaRoute, params?: RouteParams) => {
  if (route === '/') return route
  const rawSegments = route.slice(1).split('/')
  const resolved: string[] = []
  for (const segment of rawSegments) {
    const optionalCatchAll = segment.match(/^\[\[\.\.\.(.+)\]\]$/)
    if (optionalCatchAll) {
      const key = optionalCatchAll[1]
      const value = params?.[key]
      if (!value) continue
      if (!Array.isArray(value)) {
        throw new Error(`Expected array for optional catch-all "${key}" of route "${route}"`)
      }
      for (const item of value) {
        if (typeof item !== 'string' && typeof item !== 'number') {
          throw new Error(`Invalid value for optional catch-all "${key}" of route "${route}"`)
        }
        resolved.push(encodeParam(item))
      }
      continue
    }
    const catchAll = segment.match(/^\[\.\.\.(.+)\]$/)
    if (catchAll) {
      const key = catchAll[1]
      const value = params?.[key]
      if (!Array.isArray(value) || value.length === 0) {
        throw new Error(`Expected non-empty array for catch-all "${key}" of route "${route}"`)
      }
      for (const item of value) {
        if (typeof item !== 'string' && typeof item !== 'number') {
          throw new Error(`Invalid value for catch-all "${key}" of route "${route}"`)
        }
        resolved.push(encodeParam(item))
      }
      continue
    }
    const dynamic = segment.match(/^\[(.+)\]$/)
    if (dynamic) {
      const key = dynamic[1]
      const value = params?.[key]
      if (value === undefined) {
        throw new Error(`Missing value for dynamic segment "${key}" of route "${route}"`)
      }
      if (typeof value !== 'string' && typeof value !== 'number') {
        throw new Error(`Invalid value for dynamic segment "${key}" of route "${route}"`)
      }
      resolved.push(encodeParam(value))
      continue
    }
    if (segment.length > 0) {
      resolved.push(segment)
    }
  }
  return resolved.length ? `/${resolved.join('/')}` : '/'
}

const buildSearchString = (searchParams: Record<string, unknown> | undefined) => {
  if (!searchParams) return undefined
  const serialized = serializeQuery(searchParams)
  return serialized ? `?${serialized}` : undefined
}

export const buildUrl = (args: NextjsSuamaRouteInput) => {
  const params = 'params' in args ? args.params : undefined
  const searchParams =
    'searchParams' in args
      ? (args as typeof args & { searchParams?: Record<string, unknown> }).searchParams
      : undefined
  const pathname = buildPath(args.route, params as RouteParams | undefined)
  const search = buildSearchString(searchParams as Record<string, unknown> | undefined)
  const href = search ? `${pathname}${search}` : pathname
  return {
    pathname,
    href,
    ...(search ? { search } : {}),
    ...(searchParams !== undefined ? { searchParams } : {}),
  }
}
