import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ReactScan } from '~/components/react-scan'
import { Toast } from '~/components/ui/intent-ui/toast'
import { Providers } from '~/components/ui/providers/providers'
import { Root } from '~/hooks/use-confirm'
import type { NextLayoutProps } from '~/types'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SUAMA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: NextLayoutProps) {
  return (
    <html lang="ja">
      {process.env.NODE_ENV === 'development' && <ReactScan />}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Root />
          <Toast />
          {children}
        </Providers>
      </body>
    </html>
  )
}
