// AUTO-GENERATED by next-typed-url. DO NOT EDIT.
import { nextjs_suamaUrl as __nextjs_suamaUrl } from './nextjs-suama'

export { __nextjs_suamaUrl as nextjs_suamaUrl }
export type {
  NextjsSuamaRoute as NextjsSuamaRoute,
  NextjsSuamaRouteInput as NextjsSuamaRouteInput,
} from './nextjs-suama'

export const urls = __nextjs_suamaUrl
